#!/bin/bash
#autor: root
#Fecha: Mon Apr 17 16:12:38 MDT 2017
#Comentario: Instalador del monitor

(( EUID != 0 )) && exec sudo -- "$0" "$@"

app_name="sysadmin-monitor"
folder="/etc/cron.$app_name"

clear
echo "Cual correo deseas usar para enviar avisos? "
read correo
echo "Cual es la contrasena? "
read correo_pass
echo "A cual correo deseas enviar los avisos? "
read correo_para
echo "Para hacer los respaldos en Dropbox se necesita un Access Token"
echo "Mas informacion: https://www.dropbox.com/developers/"
echo "Ingresa el Token de Acceso: "
read access_token
echo "Cada cuantos minutos deseas ejecutar la tarea?"
read minutes
salir="y"
mkdir $folder
rm $folder/krystal.conf 2> /dev/null
echo "ORDENADORES A MONITOREAR"
while [ "$salir" = "y" ]; do
	echo "Ingresa la direccion IP: "
	read ip
	echo "Ingresa el usuario: "
	read usuario
	echo "Ingresa la contrasena del usuario: "
	read contrasena
	echo "$ip,$usuario,$contrasena" >> $folder/krystal.conf
	echo "Desea agregar otro ordenador? (y)es/(n)o"
	read -n1 salir
done
echo $correo_para  >> $folder/krystal.conf
echo $access_token >> $folder/krystal.conf
cp mailconfig ~/.mailrc
echo "set smtp-auth-user=$correo" >> ~/.mailrc
echo "set smtp-auth-password=$correo_pass" >> ~/.mailrc
echo "set from=$correo" >> ~/.mailrc
mkdir ~/$app_name
cp ./krystal.sh $folder/krystal.sh && chmod +x $folder/krystal.sh
cp ./exp_copy_id $folder/exp_copy_id && chmod +x $folder/exp_copy_id
if [ -x $folder/krystal.sh ]; then
crontab - << EOF
$(crontab -l)
# sysadmin-monitor
*/$minutes * * * *  $folder/krystal.sh >> ~/$app_name/output.log
# end sysadmin-monitor
EOF
fi
echo ""
echo "Instalación finalizada :)"
exit 0
