#!/bin/bash
#autor: root
#Fecha: Fri Apr 21 16:55:47 MDT 2017
#Comentario: Desinstalador

app_name="sysadmin-monitor"
folder="/etc/cron.$app_name"

rm -R $folder
crontab - << EOF
$(grep -v $app_name <(crontab -l))
EOF
echo "Desinstalación Completada :)"
exit 0
